### ISSUE TITLE
More force?

### ISSUE THREAD

**Issue by A1igator** [oxters168/VRPhysicsHands#2]
Firstly, this is amazing and thank you so much for providing it. I was wondering if there is a way to increase the force on the fingers. So it would bend at a higher threshold of force.

**Comment by oxters168** [comment]
The bending of the fingers happens through the ConfigurableJoints on the hands. You should be able to increase the force in it to make the bending faster. To modify all fingers at once, you can search in the scene hierarchy for ‘t:ConfigurableJoint’. That will list only the things in the scene with that component.

**Comment by A1igator** [comment]
Based on my tinkering I think the drives (x drive, y drive, z drive) are what does it on the configurable joint. I do think it would still be easier if this was just a field on your Hand Emulator script, because I have more configurable joints than just your hand so it's still quite tedious to manually select them all and change the drives. I can make a pull request if you'd like.

**Comment by oxters168** [comment]
Go for it! I'd really appreciate the help. If you don't get a chance to, I can also implement it if you want.
