### ISSUE TITLE
how to use this in my VR scene based on WebXR

### ISSUE THREAD

**Issue by addy1997** [oxters168/VRPhysicsHands#6]
Hi @oxters168.

This is an amazing project. Can I use this in my VR scene based on [aframe](https://aframe.io/)?

**Comment by oxters168** [comment]
Thank you! My hand physics solution is built on Unity and it looks like A-Frame is not something that is used with Unity. So out of the box it does not seem like it would work. Feel free to port it over if you'd like though.
